export enum GeneOverlapField {
  NONE = 'NONE',
  JACCARD = 'JACCARD',
  P_VALUE = 'P_VALUE',
  FDR = 'FDR',
  TARGET_SIGNATURE = 'TARGET_SIGNATURE',
  SOURCE_COMPARISON_TYPE = 'SOURCE_COMPARISON_TYPE',
  TARGET_COMPARISON_TYPE = 'TARGET_COMPARISON_TYPE'
}
